"""initial_schema

Revision ID: 8f0223843258
Revises: None
Create Date: 2026-08-13 23:45:16.289056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0223843258'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_activity_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_activity_log_id'), 'audit_activity_log', ['id'], unique=False)
    op.create_table('auth_password_reset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_password_reset_id'), 'auth_password_reset', ['id'], unique=False)
    op.create_table('auth_verification_token',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_verification_token_id'), 'auth_verification_token', ['id'], unique=False)
    op.create_table('catalog_category',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_category_id'), 'catalog_category', ['id'], unique=False)
    op.create_table('catalog_collection',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_collection_id'), 'catalog_collection', ['id'], unique=False)
    op.create_table('catalog_product',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_product_id'), 'catalog_product', ['id'], unique=False)
    op.create_table('catalog_product_tag',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_product_tag_id'), 'catalog_product_tag', ['id'], unique=False)
    op.create_table('catalog_tag',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_tag_id'), 'catalog_tag', ['id'], unique=False)
    op.create_table('chatbot_chat_retrieval',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_chat_retrieval_id'), 'chatbot_chat_retrieval', ['id'], unique=False)
    op.create_table('chatbot_conversation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_conversation_id'), 'chatbot_conversation', ['id'], unique=False)
    op.create_table('chatbot_knowledge_chunk',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_knowledge_chunk_id'), 'chatbot_knowledge_chunk', ['id'], unique=False)
    op.create_table('chatbot_knowledge_document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_knowledge_document_id'), 'chatbot_knowledge_document', ['id'], unique=False)
    op.create_table('chatbot_message',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_message_id'), 'chatbot_message', ['id'], unique=False)
    op.create_table('checkout_checkout',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_checkout_id'), 'checkout_checkout', ['id'], unique=False)
    op.create_table('checkout_payment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_payment_id'), 'checkout_payment', ['id'], unique=False)
    op.create_table('checkout_payment_transaction',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_payment_transaction_id'), 'checkout_payment_transaction', ['id'], unique=False)
    op.create_table('commerce_cart',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commerce_cart_id'), 'commerce_cart', ['id'], unique=False)
    op.create_table('commerce_cart_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commerce_cart_item_id'), 'commerce_cart_item', ['id'], unique=False)
    op.create_table('commerce_coupon',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commerce_coupon_id'), 'commerce_coupon', ['id'], unique=False)
    op.create_table('commerce_coupon_redemption',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commerce_coupon_redemption_id'), 'commerce_coupon_redemption', ['id'], unique=False)
    op.create_table('commerce_wishlist',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commerce_wishlist_id'), 'commerce_wishlist', ['id'], unique=False)
    op.create_table('commerce_wishlist_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commerce_wishlist_item_id'), 'commerce_wishlist_item', ['id'], unique=False)
    op.create_table('customer_address',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_address_id'), 'customer_address', ['id'], unique=False)
    op.create_table('employee_department',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_department_id'), 'employee_department', ['id'], unique=False)
    op.create_index(op.f('ix_employee_department_name'), 'employee_department', ['name'], unique=True)
    op.create_table('inventory_inventory_location',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_inventory_location_id'), 'inventory_inventory_location', ['id'], unique=False)
    op.create_table('inventory_inventory_movement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_inventory_movement_id'), 'inventory_inventory_movement', ['id'], unique=False)
    op.create_table('inventory_inventory_stock',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_inventory_stock_id'), 'inventory_inventory_stock', ['id'], unique=False)
    op.create_table('inventory_stock_reservation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_stock_reservation_id'), 'inventory_stock_reservation', ['id'], unique=False)
    op.create_table('inventory_stock_transfer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_stock_transfer_id'), 'inventory_stock_transfer', ['id'], unique=False)
    op.create_table('inventory_warehouse',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_warehouse_id'), 'inventory_warehouse', ['id'], unique=False)
    op.create_table('media_marketing_media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_marketing_media_id'), 'media_marketing_media', ['id'], unique=False)
    op.create_table('media_media_asset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_media_asset_id'), 'media_media_asset', ['id'], unique=False)
    op.create_table('media_media_review',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_media_review_id'), 'media_media_review', ['id'], unique=False)
    op.create_table('media_product_media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_product_media_id'), 'media_product_media', ['id'], unique=False)
    op.create_table('notification_notification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_notification_id'), 'notification_notification', ['id'], unique=False)
    op.create_table('orders_order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders_order', ['id'], unique=False)
    op.create_table('orders_order_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_item_id'), 'orders_order_item', ['id'], unique=False)
    op.create_table('orders_order_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_status_history_id'), 'orders_order_status_history', ['id'], unique=False)
    op.create_table('orders_return_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_return_item_id'), 'orders_return_item', ['id'], unique=False)
    op.create_table('orders_return_order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_return_order_id'), 'orders_return_order', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('pricing_price_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_price_history_id'), 'pricing_price_history', ['id'], unique=False)
    op.create_table('pricing_product_price',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_product_price_id'), 'pricing_product_price', ['id'], unique=False)
    op.create_table('pricing_tax_rate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_tax_rate_id'), 'pricing_tax_rate', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True, comment='NULL for Facebook OAuth users who declined email permission'),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='NULL for OAuth-only users who have no password'),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('variants_attribute',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variants_attribute_id'), 'variants_attribute', ['id'], unique=False)
    op.create_table('variants_attribute_value',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variants_attribute_value_id'), 'variants_attribute_value', ['id'], unique=False)
    op.create_table('variants_product_attribute',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variants_product_attribute_id'), 'variants_product_attribute', ['id'], unique=False)
    op.create_table('variants_product_variant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variants_product_variant_id'), 'variants_product_variant', ['id'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('loyalty_tier', sa.String(length=50), nullable=False),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_customer_profiles_user_id'), 'customer_profiles', ['user_id'], unique=True)
    op.create_table('employee_section',
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['employee_department.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_section_department_id'), 'employee_section', ['department_id'], unique=False)
    op.create_index(op.f('ix_employee_section_id'), 'employee_section', ['id'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='OAuth provider name: google | facebook'),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False, comment='Unique user ID issued by the OAuth provider'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email returned by the OAuth provider'),
    sa.Column('access_token', sa.String(length=2048), nullable=True, comment='Provider access token (stored for potential API calls)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_user')
    )
    op.create_index(op.f('ix_oauth_accounts_id'), 'oauth_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_provider'), 'oauth_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('employee_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['employee_department.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['employee_section.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_profiles_department_id'), 'employee_profiles', ['department_id'], unique=False)
    op.create_index(op.f('ix_employee_profiles_employee_code'), 'employee_profiles', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employee_profiles_id'), 'employee_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_employee_profiles_section_id'), 'employee_profiles', ['section_id'], unique=False)
    op.create_index(op.f('ix_employee_profiles_user_id'), 'employee_profiles', ['user_id'], unique=True)
    op.create_table('employee_attendance',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_attendance_attendance_date'), 'employee_attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_employee_attendance_employee_id'), 'employee_attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_attendance_id'), 'employee_attendance', ['id'], unique=False)
    op.create_table('employee_performance',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_period', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_performance_employee_id'), 'employee_performance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_performance_id'), 'employee_performance', ['id'], unique=False)
    op.create_index(op.f('ix_employee_performance_review_date'), 'employee_performance', ['review_date'], unique=False)
    op.create_table('employee_target',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('achieved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_target_employee_id'), 'employee_target', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_target_id'), 'employee_target', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_target_id'), table_name='employee_target')
    op.drop_index(op.f('ix_employee_target_employee_id'), table_name='employee_target')
    op.drop_table('employee_target')
    op.drop_index(op.f('ix_employee_performance_review_date'), table_name='employee_performance')
    op.drop_index(op.f('ix_employee_performance_id'), table_name='employee_performance')
    op.drop_index(op.f('ix_employee_performance_employee_id'), table_name='employee_performance')
    op.drop_table('employee_performance')
    op.drop_index(op.f('ix_employee_attendance_id'), table_name='employee_attendance')
    op.drop_index(op.f('ix_employee_attendance_employee_id'), table_name='employee_attendance')
    op.drop_index(op.f('ix_employee_attendance_attendance_date'), table_name='employee_attendance')
    op.drop_table('employee_attendance')
    op.drop_index(op.f('ix_employee_profiles_user_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_section_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_employee_code'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_department_id'), table_name='employee_profiles')
    op.drop_table('employee_profiles')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_provider'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_employee_section_id'), table_name='employee_section')
    op.drop_index(op.f('ix_employee_section_department_id'), table_name='employee_section')
    op.drop_table('employee_section')
    op.drop_index(op.f('ix_customer_profiles_user_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_variants_product_variant_id'), table_name='variants_product_variant')
    op.drop_table('variants_product_variant')
    op.drop_index(op.f('ix_variants_product_attribute_id'), table_name='variants_product_attribute')
    op.drop_table('variants_product_attribute')
    op.drop_index(op.f('ix_variants_attribute_value_id'), table_name='variants_attribute_value')
    op.drop_table('variants_attribute_value')
    op.drop_index(op.f('ix_variants_attribute_id'), table_name='variants_attribute')
    op.drop_table('variants_attribute')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_pricing_tax_rate_id'), table_name='pricing_tax_rate')
    op.drop_table('pricing_tax_rate')
    op.drop_index(op.f('ix_pricing_product_price_id'), table_name='pricing_product_price')
    op.drop_table('pricing_product_price')
    op.drop_index(op.f('ix_pricing_price_history_id'), table_name='pricing_price_history')
    op.drop_table('pricing_price_history')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_orders_return_order_id'), table_name='orders_return_order')
    op.drop_table('orders_return_order')
    op.drop_index(op.f('ix_orders_return_item_id'), table_name='orders_return_item')
    op.drop_table('orders_return_item')
    op.drop_index(op.f('ix_orders_order_status_history_id'), table_name='orders_order_status_history')
    op.drop_table('orders_order_status_history')
    op.drop_index(op.f('ix_orders_order_item_id'), table_name='orders_order_item')
    op.drop_table('orders_order_item')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders_order')
    op.drop_table('orders_order')
    op.drop_index(op.f('ix_notification_notification_id'), table_name='notification_notification')
    op.drop_table('notification_notification')
    op.drop_index(op.f('ix_media_product_media_id'), table_name='media_product_media')
    op.drop_table('media_product_media')
    op.drop_index(op.f('ix_media_media_review_id'), table_name='media_media_review')
    op.drop_table('media_media_review')
    op.drop_index(op.f('ix_media_media_asset_id'), table_name='media_media_asset')
    op.drop_table('media_media_asset')
    op.drop_index(op.f('ix_media_marketing_media_id'), table_name='media_marketing_media')
    op.drop_table('media_marketing_media')
    op.drop_index(op.f('ix_inventory_warehouse_id'), table_name='inventory_warehouse')
    op.drop_table('inventory_warehouse')
    op.drop_index(op.f('ix_inventory_stock_transfer_id'), table_name='inventory_stock_transfer')
    op.drop_table('inventory_stock_transfer')
    op.drop_index(op.f('ix_inventory_stock_reservation_id'), table_name='inventory_stock_reservation')
    op.drop_table('inventory_stock_reservation')
    op.drop_index(op.f('ix_inventory_inventory_stock_id'), table_name='inventory_inventory_stock')
    op.drop_table('inventory_inventory_stock')
    op.drop_index(op.f('ix_inventory_inventory_movement_id'), table_name='inventory_inventory_movement')
    op.drop_table('inventory_inventory_movement')
    op.drop_index(op.f('ix_inventory_inventory_location_id'), table_name='inventory_inventory_location')
    op.drop_table('inventory_inventory_location')
    op.drop_index(op.f('ix_employee_department_name'), table_name='employee_department')
    op.drop_index(op.f('ix_employee_department_id'), table_name='employee_department')
    op.drop_table('employee_department')
    op.drop_index(op.f('ix_customer_address_id'), table_name='customer_address')
    op.drop_table('customer_address')
    op.drop_index(op.f('ix_commerce_wishlist_item_id'), table_name='commerce_wishlist_item')
    op.drop_table('commerce_wishlist_item')
    op.drop_index(op.f('ix_commerce_wishlist_id'), table_name='commerce_wishlist')
    op.drop_table('commerce_wishlist')
    op.drop_index(op.f('ix_commerce_coupon_redemption_id'), table_name='commerce_coupon_redemption')
    op.drop_table('commerce_coupon_redemption')
    op.drop_index(op.f('ix_commerce_coupon_id'), table_name='commerce_coupon')
    op.drop_table('commerce_coupon')
    op.drop_index(op.f('ix_commerce_cart_item_id'), table_name='commerce_cart_item')
    op.drop_table('commerce_cart_item')
    op.drop_index(op.f('ix_commerce_cart_id'), table_name='commerce_cart')
    op.drop_table('commerce_cart')
    op.drop_index(op.f('ix_checkout_payment_transaction_id'), table_name='checkout_payment_transaction')
    op.drop_table('checkout_payment_transaction')
    op.drop_index(op.f('ix_checkout_payment_id'), table_name='checkout_payment')
    op.drop_table('checkout_payment')
    op.drop_index(op.f('ix_checkout_checkout_id'), table_name='checkout_checkout')
    op.drop_table('checkout_checkout')
    op.drop_index(op.f('ix_chatbot_message_id'), table_name='chatbot_message')
    op.drop_table('chatbot_message')
    op.drop_index(op.f('ix_chatbot_knowledge_document_id'), table_name='chatbot_knowledge_document')
    op.drop_table('chatbot_knowledge_document')
    op.drop_index(op.f('ix_chatbot_knowledge_chunk_id'), table_name='chatbot_knowledge_chunk')
    op.drop_table('chatbot_knowledge_chunk')
    op.drop_index(op.f('ix_chatbot_conversation_id'), table_name='chatbot_conversation')
    op.drop_table('chatbot_conversation')
    op.drop_index(op.f('ix_chatbot_chat_retrieval_id'), table_name='chatbot_chat_retrieval')
    op.drop_table('chatbot_chat_retrieval')
    op.drop_index(op.f('ix_catalog_tag_id'), table_name='catalog_tag')
    op.drop_table('catalog_tag')
    op.drop_index(op.f('ix_catalog_product_tag_id'), table_name='catalog_product_tag')
    op.drop_table('catalog_product_tag')
    op.drop_index(op.f('ix_catalog_product_id'), table_name='catalog_product')
    op.drop_table('catalog_product')
    op.drop_index(op.f('ix_catalog_collection_id'), table_name='catalog_collection')
    op.drop_table('catalog_collection')
    op.drop_index(op.f('ix_catalog_category_id'), table_name='catalog_category')
    op.drop_table('catalog_category')
    op.drop_index(op.f('ix_auth_verification_token_id'), table_name='auth_verification_token')
    op.drop_table('auth_verification_token')
    op.drop_index(op.f('ix_auth_password_reset_id'), table_name='auth_password_reset')
    op.drop_table('auth_password_reset')
    op.drop_index(op.f('ix_audit_activity_log_id'), table_name='audit_activity_log')
    op.drop_table('audit_activity_log')
    # ### end Alembic commands ###
